### ISSUE TITLE
Replace `protocol` parameter with `server`

### ISSUE THREAD

**Issue by fcastill** [prazolpp/flogoJson#1]
Users shouldn't need to specify the protocol to use, the protocol is given by the server declaration in the asyncapi.yml. Like here:

https://www.asyncapi.com/docs/getting-started/servers/

Instead users should pass the server name and this generator should look into servers[serverName].protocol to figure out the protocol to use.

Letting the user pass the protocol is redundant because the protocol is already specified in the server. If the user passes a protocol different than the one declared by the server then their declarations might not match and the generated trigger data might be wrong.

**Comment by prazolpp** [comment]
I think this issue is closed? :D
